feat: remove entrypoint

diff --git a/fpm-alpine/8.2/dockerfile b/fpm-alpine/8.2/dockerfile
--- a/fpm-alpine/8.2/dockerfile
+++ b/fpm-alpine/8.2/dockerfile
@@ -1,87 +1,168 @@
 FROM php:8.2-fpm-alpine3.18
 
-LABEL maintainer="Kazem Mirzaei <k90mirzaei@gmail.com>"
+# Set the maintainer label
+LABEL Maintainer="Kazem Mirzaei <k90mirzaei@gmail.com>"
+LABEL Description="PHP-FPM v8.2 with essential extensions on top of Alpine Linux."
 
-ENV USER=www
-ENV GROUP=www
+# Set environment variables for the user and group
+ENV USER www
+ENV GROUP www
 
+# Switch to root user to perform system updates and installations
 USER root
+
+# Composer - https://getcomposer.org/download/
+ARG COMPOSER_VERSION="2.5.5"
+ARG COMPOSER_SUM="566a6d1cf4be1cc3ac882d2a2a13817ffae54e60f5aa7c9137434810a5809ffc"
+
+
+#############################################
+### Install and enable PHP extensions
+#############################################
 
 # Install system dependencies
 RUN set -ex \
-    && apk add --update --no-cache --virtual .build-deps \
-        autoconf \
-        curl \
-        g++ \
-        libmemcached-dev \
-        libtool \
-        libzip-dev \
-        libxml2-dev \
-        make \
-        oniguruma-dev \
-        unzip \
-        zip \
-    \
-    && docker-php-ext-install \
-        bcmath \
-        pdo \
-        pdo_mysql \
-        mbstring \
-        exif \
-        pcntl \
-        xml \
-    \
-    # Install gd
     && apk add --update --no-cache \
+        c-client \
+        freetype \
+        ffmpeg \
+        gettext \
+        gmp \
+        icu-libs \
+        imagemagick \
+        imap \
+        libintl \
+        libjpeg-turbo \
+        libpng \
+        libpq \
+        libtool \
+        libxpm \
+        libxslt \
+        libzip \
+        make \
+        tzdata
+
+# Development dependencies
+RUN set -ex \
+    && apk add --update --no-cache \
+        autoconf \
+        curl-dev \
+        freetype-dev \
+        g++ \
+        gcc \
+        gettext-dev \
+        git \
+        gmp-dev \
+        icu-dev \
+        imagemagick-dev \
+        imap-dev \
+        krb5-dev \
+        libc-dev \
         libjpeg-turbo-dev \
         libpng-dev \
         libwebp-dev \
-        freetype-dev \
-    && docker-php-ext-configure gd --with-jpeg --with-freetype \
-	&& docker-php-ext-install gd \
+        libxml2-dev \
+        libxpm-dev \
+        libxslt-dev \
+        libzip-dev \
+        pcre-dev \
+        pkgconf \
+        zlib-dev \
     \
-    # Install ffmpeg
-    && apk add --update --no-cache ffmpeg \
+    ################################
+    # Install PHP extensions
+    ################################
+    \
+    # Install gd
+    && ln -s /usr/lib/$(apk --print-arch)-linux-gnu/libXpm.* /usr/lib/ \
+    && docker-php-ext-configure gd \
+        --enable-gd \
+        --with-webp \
+        --with-jpeg \
+        --with-xpm \
+        --with-freetype \
+        --enable-gd-jis-conv \
+    && docker-php-ext-install -j$(nproc) gd \
+    && true \
+    \
+    # Install gettext
+    && docker-php-ext-install -j$(nproc) gettext \
+    && true \
+    \
+    # Install gmp
+    && docker-php-ext-install -j$(nproc) gmp \
+    && true \
+    \
+    # Install bcmath
+    && docker-php-ext-install -j$(nproc) bcmath \
+    && true \
+    \
+    # Install exif
+    && docker-php-ext-install -j$(nproc) exif \
+    && true \
+    \
+    # Install imap
+    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl --with-imap \
+    && docker-php-ext-install -j$(nproc) imap \
+    && true \
+    \
+    # Install imagick
+    && pecl install imagick \
+    && docker-php-ext-enable imagick \
+    && true \
+    \
+    # Install intl
+    && docker-php-ext-install -j$(nproc) intl \
+    && true \
+    \
+    # Install pdo_mysql
+    && docker-php-ext-configure pdo_mysql --with-zlib-dir=/usr \
+    && docker-php-ext-install -j$(nproc) pdo pdo_mysql \
+    && true \
+    \
+    # Install pcntl
+    && docker-php-ext-install -j$(nproc) pcntl \
+    && true \
     \
     # Install redis
-    && apk --no-cache add pcre-dev ${PHPIZE_DEPS} \
-    && pecl install redis \
-    && apk del pcre-dev ${PHPIZE_DEPS} \
-    && docker-php-ext-enable redis \        
+    && pecl install --force redis \
+    && docker-php-ext-enable redis \
+    && true \
     \
-    # Install zip 
-    && docker-php-ext-configure zip \
-    && docker-php-ext-install zip \
+    # Install zip
+    && docker-php-ext-configure zip --with-zip \
+    && docker-php-ext-install -j$(nproc) zip \
+    && true \
     \
-    # Clean up
-    && apk del .build-deps \
+    # Clean up build packages
+    && docker-php-source delete \
     && rm -fr /tmp/pear \ 
     && rm -rf /tmp/* \
-    && rm -rf /var/cache/apk/*
+    && rm -rf /var/cache/apk/* \
+    && true
 
-# Get latest Composer
-COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
+# Install Composer
+RUN set -eux \
+    && curl -LO "https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar" \
+    && echo "${COMPOSER_SUM}  composer.phar" | sha256sum -c - \
+    && chmod +x composer.phar \
+    && mv composer.phar /usr/local/bin/composer \
+    && composer --version \
+    && true
 
-# Setup working directory
-WORKDIR /var/www/
+# Set the working directory
+WORKDIR /var/www
 
-# create user
+# Create a non-root user and group
 RUN getent group ${GROUP} || addgroup -g 1000 ${GROUP} 
 RUN id -u ${USER} || adduser --shell /sbin/nologin --disabled-password --no-create-home --uid 1000 --ingroup ${GROUP} ${USER}
 
-## Grant Permissions
-RUN chown -R ${USER} /var/www
+# Grant write permissions to the non-root user and group
+RUN chown -R ${USER}:${GROUP} /var/www
 
-### Select User
+# Switch to the non-root user
 USER ${USER}
 
-# Grant permission to selected user
-COPY --chown=${USER}:${GROUP} . .
-
-# Execute scripts
-COPY --chown=${USER}:${GROUP} entrypoint.sh /tmp/entrypoint.sh 
-RUN ["chmod", "+x", "/tmp/entrypoint.sh"]
-ENTRYPOINT [ "/tmp/entrypoint.sh" ]
-
-# Keep php live
-CMD [ "php-fpm" ]
+# Start PHP-FPM
+EXPOSE 9000
+CMD ["php-fpm"]
